# Generated by Django 3.1.14 on 2023-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_software_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
