# Generated by Django 3.1.14 on 2023-09-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_work_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='atcoder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='atcoder'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qiita',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='qiita'),
        ),
    ]
