# Generated by Django 3.1.14 on 2023-09-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230904_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='period',
        ),
    ]
