# Generated by Django 3.1.14 on 2023-09-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_experience_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='urlname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URLNAME'),
        ),
    ]
